
POST http://localhost:3000/api/pre-demandes
Content-Type: application/json

{
  "nom": "Test",
  "prenom": "Parcelle",
  "email": "jardinpartage.test+blocage1@gmail.com",
  "adresse": "20 rue des tests",
  "ville": "Versailles",
  "type_demande": "demande_parcelle"
}